install.packages("data.table")
library(data.table)
install.packages("lubridate")
library(lubridate)

aa<-fread("household_power_consumption.txt",nrows = 2880, skip="1/2/2007",na.strings = "?")
colnames(aa) <-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
aa$Date<-as.Date(aa$Date,format="%d/%m/%Y")
aa<-within(aa, Time <- paste(Date, Time, sep=" "))
aa <- transform(aa, Time = as.POSIXct(Time))
Sys.setlocale("LC_TIME", "English")

png(file = "plot3.png",width = 480, height = 480)
plot(aa$Time,aa$Sub_metering_1,type= "l",ylab = "Energy sub metering", xlab="")
lines(aa$Time,aa$Sub_metering_2,type= "l", col = "red")
lines(aa$Time,aa$Sub_metering_3,type= "l", col = "blue")
legend("topright", lwd = 1, col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()