install.packages("data.table")
library(data.table)
aa<-fread("household_power_consumption.txt",nrows = 2880, skip="1/2/2007")
colnames(aa) <-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
aa$Date<-as.Date(aa$Date,format="%d/%m/%Y")
aa<-within(aa, Time <- paste(Date, Time, sep=" "))
aa <- transform(aa, Time = as.POSIXct(Time))
Sys.setlocale("LC_TIME", "English")

png(file = "plot4.png",width = 480, height = 480)
par(mfrow = c(2, 2))
with(aa,{
  plot(Time,Global_active_power,type = "l",ylab= "Global Active Power (kilowatts)" ,xlab="")  
  plot(Time,Voltage,type = "l",ylab= "Voltage" ,xlab="datetime")
  plot(Time,Sub_metering_1,type= "l",ylab = "Energy sub metering", xlab="")
  lines(Time,Sub_metering_2,type= "l", col = "red")
  lines(Time,Sub_metering_3,type= "l", col = "blue")
  legend("topright", lwd = 1, col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),bty="n")
  plot(Time,Global_reactive_power,type = "l",ylab= "Global_reactive_power" ,xlab="datetime")
  })
dev.off()